// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: blobs_0x0.sql

package db

import (
	"context"
	"database/sql"
)

const deleteBlob0x0FromHash = `-- name: DeleteBlob0x0FromHash :exec
DELETE FROM blobs_0x0 WHERE hash = ?
`

func (q *Queries) DeleteBlob0x0FromHash(ctx context.Context, hash string) error {
	_, err := q.db.ExecContext(ctx, deleteBlob0x0FromHash, hash)
	return err
}

const deleteExpiredBlobs0x0 = `-- name: DeleteExpiredBlobs0x0 :exec
DELETE FROM blobs_0x0 WHERE expiry IS NOT NULL AND expiry < ?
`

func (q *Queries) DeleteExpiredBlobs0x0(ctx context.Context, expiry sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredBlobs0x0, expiry)
	return err
}

const getBlob0x0FromHash = `-- name: GetBlob0x0FromHash :one
SELECT hash, pubkey, url, size, type, expiry, created FROM blobs_0x0 WHERE hash = ? LIMIT 1
`

func (q *Queries) GetBlob0x0FromHash(ctx context.Context, hash string) (Blobs0x0, error) {
	row := q.db.QueryRowContext(ctx, getBlob0x0FromHash, hash)
	var i Blobs0x0
	err := row.Scan(
		&i.Hash,
		&i.Pubkey,
		&i.Url,
		&i.Size,
		&i.Type,
		&i.Expiry,
		&i.Created,
	)
	return i, err
}

const getBlobs0x0FromPubkey = `-- name: GetBlobs0x0FromPubkey :many
SELECT hash, pubkey, url, size, type, expiry, created FROM blobs_0x0 WHERE pubkey = ? ORDER BY created DESC
`

func (q *Queries) GetBlobs0x0FromPubkey(ctx context.Context, pubkey string) ([]Blobs0x0, error) {
	rows, err := q.db.QueryContext(ctx, getBlobs0x0FromPubkey, pubkey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Blobs0x0
	for rows.Next() {
		var i Blobs0x0
		if err := rows.Scan(
			&i.Hash,
			&i.Pubkey,
			&i.Url,
			&i.Size,
			&i.Type,
			&i.Expiry,
			&i.Created,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalStorage0x0ByPubkey = `-- name: GetTotalStorage0x0ByPubkey :one
SELECT COALESCE(SUM(size), 0) as total_size FROM blobs_0x0 WHERE pubkey = ?
`

func (q *Queries) GetTotalStorage0x0ByPubkey(ctx context.Context, pubkey string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getTotalStorage0x0ByPubkey, pubkey)
	var total_size int64
	err := row.Scan(&total_size)
	return total_size, err
}

const insertBlob0x0 = `-- name: InsertBlob0x0 :one
INSERT INTO blobs_0x0 (hash, pubkey, url, size, type, expiry, created)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING hash, pubkey, url, size, type, expiry, created
`

type InsertBlob0x0Params struct {
	Hash    string
	Pubkey  string
	Url     string
	Size    int64
	Type    string
	Expiry  sql.NullInt64
	Created int64
}

func (q *Queries) InsertBlob0x0(ctx context.Context, arg InsertBlob0x0Params) (Blobs0x0, error) {
	row := q.db.QueryRowContext(ctx, insertBlob0x0,
		arg.Hash,
		arg.Pubkey,
		arg.Url,
		arg.Size,
		arg.Type,
		arg.Expiry,
		arg.Created,
	)
	var i Blobs0x0
	err := row.Scan(
		&i.Hash,
		&i.Pubkey,
		&i.Url,
		&i.Size,
		&i.Type,
		&i.Expiry,
		&i.Created,
	)
	return i, err
}
