// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import "database/sql"

type Blob struct {
	Pubkey  string
	Hash    string
	Type    string
	Size    int64
	Blob    []byte
	Created int64
}

type Blobs0x0 struct {
	Hash    string
	Pubkey  string
	Url     string
	Size    int64
	Type    string
	Expiry  sql.NullInt64
	Created int64
}

type MimeType struct {
	Extension string
	MimeType  string
}

type Session struct {
	ID            string
	PublicKey     string
	SigningMethod string
	Mode          string
	CreatedAt     int64
	ExpiresAt     int64
	LastActive    int64
}
