// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sessions.sql

package db

import (
	"context"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions(
  id,
  public_key,
  signing_method,
  mode,
  created_at,
  expires_at,
  last_active
) VALUES (?,?,?,?,?,?,?)
RETURNING id, public_key, signing_method, mode, created_at, expires_at, last_active
`

type CreateSessionParams struct {
	ID            string
	PublicKey     string
	SigningMethod string
	Mode          string
	CreatedAt     int64
	ExpiresAt     int64
	LastActive    int64
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.PublicKey,
		arg.SigningMethod,
		arg.Mode,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.LastActive,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.SigningMethod,
		&i.Mode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActive,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, public_key, signing_method, mode, created_at, expires_at, last_active
FROM sessions
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.SigningMethod,
		&i.Mode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActive,
	)
	return i, err
}

const getSessionByPublicKey = `-- name: GetSessionByPublicKey :one
SELECT id, public_key, signing_method, mode, created_at, expires_at, last_active
FROM sessions
WHERE public_key = ?
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetSessionByPublicKey(ctx context.Context, publicKey string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByPublicKey, publicKey)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.SigningMethod,
		&i.Mode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastActive,
	)
	return i, err
}

const updateSessionLastActive = `-- name: UpdateSessionLastActive :exec
UPDATE sessions
SET last_active = ?
WHERE id = ?
`

type UpdateSessionLastActiveParams struct {
	LastActive int64
	ID         string
}

func (q *Queries) UpdateSessionLastActive(ctx context.Context, arg UpdateSessionLastActiveParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionLastActive, arg.LastActive, arg.ID)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const getActiveSessions = `-- name: GetActiveSessions :many
SELECT id, public_key, signing_method, mode, created_at, expires_at, last_active
FROM sessions
WHERE expires_at > ?
ORDER BY last_active DESC
`

func (q *Queries) GetActiveSessions(ctx context.Context, expiresAt int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getActiveSessions, expiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.PublicKey,
			&i.SigningMethod,
			&i.Mode,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
